name: project4
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  contained_tab_bar_view: ^0.8.0
  salomon_bottom_bar: ^3.3.2
  image_picker: ^1.1.2
  shimmer_animation: ^2.2.1
  material_dialogs: ^1.1.5
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/graduation_images/
    - assets/wedding_images/
    - assets/event_images/
    - assets/offers/
    - assets/anouncment_images/
